### ISSUE TITLE
Remove old files

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/reopt-vcg#96]
Based on my (somewhat limited given the duration of this project) experiences, the following top level directories seem likely to no longer be of use going forward:

```
concrete-vcg/
lean/
old-lean4/
test-programs/
```

I think it would be useful to remove these and move the contents of `lean4` into the root of the repository.

**Comment by joehendrix** [comment]
This matches my understanding.  @simonjwinwood Do you have any objections to removing them?
